
export const theoryClasses = [
    { code: 'A1', day: 'Monday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'F1', day: 'Monday', startTime: '9:00 AM', endTime: '9:50 AM' },
    { code: 'D1', day: 'Monday', startTime: '10:00 AM', endTime: '10:50 AM' },
    { code: 'TB1', day: 'Monday', startTime: '11:00 AM', endTime: '11:50 AM' },
    { code: 'TG1', day: 'Monday', startTime: '12:00 PM', endTime: '12:50 PM' },
    { code: 'A2', day: 'Monday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'F2', day: 'Monday', startTime: '3:00 PM', endTime: '3:50 PM' },
    { code: 'D2', day: 'Monday', startTime: '4:00 PM', endTime: '4:50 PM' },
    { code: 'TB2', day: 'Monday', startTime: '5:00 PM', endTime: '5:50 PM' },
    { code: 'TG2', day: 'Monday', startTime: '6:00 PM', endTime: '6:50 PM' },
    { code: 'V3', day: 'Monday', startTime: '7:01 PM', endTime: '7:50 PM' },
    
    { code: 'B1', day: 'Tuesday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'G1', day: 'Tuesday', startTime: '9:00 AM', endTime: '9:50 AM' },
    { code: 'E1', day: 'Tuesday', startTime: '10:00 AM', endTime: '10:50 AM' },
    { code: 'TC1', day: 'Tuesday', startTime: '11:00 AM', endTime: '11:50 AM' },
    { code: 'TAA1', day: 'Tuesday', startTime: '12:00 PM', endTime: '12:50 PM' },
    { code: 'B2', day: 'Tuesday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'G2', day: 'Tuesday', startTime: '3:00 PM', endTime: '3:50 PM' },
    { code: 'E2', day: 'Tuesday', startTime: '4:00 PM', endTime: '4:50 PM' },
    { code: 'TC2', day: 'Tuesday', startTime: '5:00 PM', endTime: '5:50 PM' },
    { code: 'TAA2', day: 'Tuesday', startTime: '6:00 PM', endTime: '6:50 PM' },
    { code: 'V4', day: 'Tuesday', startTime: '7:01 PM', endTime: '7:50 PM' },
    
    { code: 'C1', day: 'Wednesday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'A1', day: 'Wednesday', startTime: '9:00 AM', endTime: '9:50 AM' },
    { code: 'F1', day: 'Wednesday', startTime: '10:00 AM', endTime: '10:50 AM' },
    { code: 'V1', day: 'Wednesday', startTime: '11:00 AM', endTime: '11:50 AM' },
    { code: 'V2', day: 'Wednesday', startTime: '12:00 PM', endTime: '12:50 PM' },
    { code: 'C2', day: 'Wednesday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'A2', day: 'Wednesday', startTime: '3:00 PM', endTime: '3:50 PM' },
    { code: 'F2', day: 'Wednesday', startTime: '4:00 PM', endTime: '4:50 PM' },
    { code: 'TD2', day: 'Wednesday', startTime: '5:00 PM', endTime: '5:50 PM' },
    { code: 'TBB2', day: 'Wednesday', startTime: '6:00 PM', endTime: '6:50 PM' },
    { code: 'V5', day: 'Wednesday', startTime: '7:01 PM', endTime: '7:50 PM' },
    
    { code: 'D1', day: 'Thursday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'B1', day: 'Thursday', startTime: '9:00 AM', endTime: '9:50 AM' },
    { code: 'G1', day: 'Thursday', startTime: '10:00 AM', endTime: '10:50 AM' },
    { code: 'TE1', day: 'Thursday', startTime: '11:00 AM', endTime: '11:50 AM' },
    { code: 'TCC1', day: 'Thursday', startTime: '12:00 PM', endTime: '12:50 PM' },
    { code: 'D2', day: 'Thursday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'B2', day: 'Thursday', startTime: '3:00 PM', endTime: '3:50 PM' },
    { code: 'G2', day: 'Thursday', startTime: '4:00 PM', endTime: '4:50 PM' },
    { code: 'TE2', day: 'Thursday', startTime: '5:00 PM', endTime: '5:50 PM' },
    { code: 'TCC2', day: 'Thursday', startTime: '6:00 PM', endTime: '6:50 PM' },
    { code: 'V6', day: 'Thursday', startTime: '7:01 PM', endTime: '7:50 PM' },
    
    { code: 'E1', day: 'Friday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'C1', day: 'Friday', startTime: '9:00 AM', endTime: '9:50 AM' },
    { code: 'TA1', day: 'Friday', startTime: '10:00 AM', endTime: '10:50 AM' },
    { code: 'TF1', day: 'Friday', startTime: '11:00 AM', endTime: '11:50 AM' },
    { code: 'TD1', day: 'Friday', startTime: '12:00 PM', endTime: '12:50 PM' },
    { code: 'E2', day: 'Friday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'C2', day: 'Friday', startTime: '3:00 PM', endTime: '3:50 PM' },
    { code: 'TA2', day: 'Friday', startTime: '4:00 PM', endTime: '4:50 PM' },
    { code: 'TF2', day: 'Friday', startTime: '5:00 PM', endTime: '5:50 PM' },
    { code: 'TDD2', day: 'Friday', startTime: '6:00 PM', endTime: '6:50 PM' },
    { code: 'V7', day: 'Friday', startTime: '7:01 PM', endTime: '7:50 PM' }
  ];

  export const labClasses = [
    { code: 'L1', day: 'Monday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'L2', day: 'Monday', startTime: '8:51 AM', endTime: '9:40 AM' },
    { code: 'L3', day: 'Monday', startTime: '9:51 AM', endTime: '10:40 AM' },
    { code: 'L4', day: 'Monday', startTime: '10:41 AM', endTime: '11:30 AM' },
    { code: 'L5', day: 'Monday', startTime: '11:40 AM', endTime: '12:30 PM' },
    { code: 'L6', day: 'Monday', startTime: '12:31 PM', endTime: '1:20 PM' },
    { code: 'L31', day: 'Monday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'L32', day: 'Monday', startTime: '2:51 PM', endTime: '3:40 PM' },
    { code: 'L33', day: 'Monday', startTime: '3:51 PM', endTime: '4:40 PM' },
    { code: 'L34', day: 'Monday', startTime: '4:41 PM', endTime: '5:30 PM' },
    { code: 'L35', day: 'Monday', startTime: '5:40 PM', endTime: '6:30 PM' },
    { code: 'L36', day: 'Monday', startTime: '6:31 PM', endTime: '7:20 PM' },
    
    { code: 'L7', day: 'Tuesday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'L8', day: 'Tuesday', startTime: '8:51 AM', endTime: '9:40 AM' },
    { code: 'L9', day: 'Tuesday', startTime: '9:51 AM', endTime: '10:40 AM' },
    { code: 'L10', day: 'Tuesday', startTime: '10:41 AM', endTime: '11:30 AM' },
    { code: 'L11', day: 'Tuesday', startTime: '11:40 AM', endTime: '12:30 PM' },
    { code: 'L12', day: 'Tuesday', startTime: '12:31 PM', endTime: '1:20 PM' },
    { code: 'L37', day: 'Tuesday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'L38', day: 'Tuesday', startTime: '2:51 PM', endTime: '3:40 PM' },
    { code: 'L39', day: 'Tuesday', startTime: '3:51 PM', endTime: '4:40 PM' },
    { code: 'L40', day: 'Tuesday', startTime: '4:41 PM', endTime: '5:30 PM' },
    { code: 'L41', day: 'Tuesday', startTime: '5:40 PM', endTime: '6:30 PM' },
    { code: 'L42', day: 'Tuesday', startTime: '6:31 PM', endTime: '7:20 PM' },
    
    { code: 'L13', day: 'Wednesday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'L14', day: 'Wednesday', startTime: '8:51 AM', endTime: '9:40 AM' },
    { code: 'L15', day: 'Wednesday', startTime: '9:51 AM', endTime: '10:40 AM' },
    { code: 'L16', day: 'Wednesday', startTime: '10:41 AM', endTime: '11:30 AM' },
    { code: 'L17', day: 'Wednesday', startTime: '11:40 AM', endTime: '12:30 PM' },
    { code: 'L18', day: 'Wednesday', startTime: '12:31 PM', endTime: '1:20 PM' },
    { code: 'L43', day: 'Wednesday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'L44', day: 'Wednesday', startTime: '2:51 PM', endTime: '3:40 PM' },
    { code: 'L45', day: 'Wednesday', startTime: '3:51 PM', endTime: '4:40 PM' },
    { code: 'L46', day: 'Wednesday', startTime: '4:41 PM', endTime: '5:30 PM' },
    { code: 'L47', day: 'Wednesday', startTime: '5:40 PM', endTime: '6:30 PM' },
    { code: 'L48', day: 'Wednesday', startTime: '6:31 PM', endTime: '7:20 PM' },
    
    { code: 'L19', day: 'Thursday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'L20', day: 'Thursday', startTime: '8:51 AM', endTime: '9:40 AM' },
    { code: 'L21', day: 'Thursday', startTime: '9:51 AM', endTime: '10:40 AM' },
    { code: 'L22', day: 'Thursday', startTime: '10:41 AM', endTime: '11:30 AM' },
    { code: 'L23', day: 'Thursday', startTime: '11:40 AM', endTime: '12:30 PM' },
    { code: 'L24', day: 'Thursday', startTime: '12:31 PM', endTime: '1:20 PM' },
    { code: 'L49', day: 'Thursday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'L50', day: 'Thursday', startTime: '2:51 PM', endTime: '3:40 PM' },
    { code: 'L51', day: 'Thursday', startTime: '3:51 PM', endTime: '4:40 PM' },
    { code: 'L52', day: 'Thursday', startTime: '4:41 PM', endTime: '5:30 PM' },
    { code: 'L53', day: 'Thursday', startTime: '5:40 PM', endTime: '6:30 PM' },
    { code: 'L54', day: 'Thursday', startTime: '6:31 PM', endTime: '7:20 PM' },
    
    { code: 'L25', day: 'Friday', startTime: '8:00 AM', endTime: '8:50 AM' },
    { code: 'L26', day: 'Friday', startTime: '8:51 AM', endTime: '9:40 AM' },
    { code: 'L27', day: 'Friday', startTime: '9:51 AM', endTime: '10:40 AM' },
    { code: 'L28', day: 'Friday', startTime: '10:41 AM', endTime: '11:30 AM' },
    { code: 'L29', day: 'Friday', startTime: '11:40 AM', endTime: '12:30 PM' },
    { code: 'L30', day: 'Friday', startTime: '12:31 PM', endTime: '1:20 PM' },
    { code: 'L55', day: 'Friday', startTime: '2:00 PM', endTime: '2:50 PM' },
    { code: 'L56', day: 'Friday', startTime: '2:51 PM', endTime: '3:40 PM' },
    { code: 'L57', day: 'Friday', startTime: '3:51 PM', endTime: '4:40 PM' },
    { code: 'L58', day: 'Friday', startTime: '4:41 PM', endTime: '5:30 PM' },
    { code: 'L59', day: 'Friday', startTime: '5:40 PM', endTime: '6:30 PM' },
    { code: 'L60', day: 'Friday', startTime: '6:31 PM', endTime: '7:20 PM' }
  ];
