// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// To change this configuration, update the Google Cloud project
// associated with this project.
export const firebaseConfig = {
  "projectId": "studio-5664654425-1c128",
  "appId": "1:159989474305:web:4e1fa5b129d829ca1c4c00",
  "apiKey": "AIzaSyCfnqLOmGvqsHbjFele4gukHnJI_Qm3Zko",
  "authDomain": "studio-5664654425-1c128.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "159989474305",
  "storageBucket": "studio-5664654425-1c128.appspot.com"
};
